### ISSUE TITLE
Please reference original source of the cover page

### ISSUE THREAD

**Issue by skgsergio** [aherranz/tfg_latex#1]
That cover page is the work of several anonymous students that wanted to share its work and I tried to improve it and make it more visible.

It won't make a difference but, instead of keeping all the credit yourself you can honor those students as I tried to do myself.

The original source of the cover page can be found at https://github.com/skgsergio/Portada-UPM-ETSIINF

**Comment by aherranz** [comment]
Hi Sergio, I've tried my best with: https://github.com/skgsergio/Portada-UPM-ETSIINF#licencia

Do you think is enough?

Kind regards.

**Comment by skgsergio** [comment]
Thanks.
